it("should handle exception", async () => {
  
});